wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693381898.347187
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      3:
      - 7
      - 23
      4: 3.9.17
      5: 0.15.9
      6: 4.11.3
      8:
      - 1
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
